#!/bin/sh

bspc config border_width       2
bspc config window_gap         0
bspc config split_ratio        0.50

bspc config borderless_monocle    true
bspc config gapless_monocle       true
#bspc config auto_alternate        false
#bspc config auto_cancel           false

# create new windows on right instead of left
bspc config initial_polarity      second_child

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config focus_follows_pointer false
bspc config click_to_focus        true

# application rules
bspc rule -a floating state=floating
bspc rule -a ds state=floating
bspc rule -a feh state=floating
bspc rule -a turry state=floating
bspc rule -a Steam follow=no

bspc config external_rules_command ~/.config/bspwm/rules

HOST=$(hostname)
if [[ "$HOST" == "desktop" ]] ; then
    bspc monitor DVI-1 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 10
    bspc config -m HDMI-0 top_padding 18
elif [[ "$HOST" == "laptop" ]] ; then
    bspc monitor eDP1 -d I II III IV V
fi

#compton --config $HOME/.config/compton/compton.conf -b

#bar &
