#!/bin/sh

bspc config border_width       2
bspc config window_gap         4

bspc config split_ratio         0.50
bspc config focus_by_distance   true

# application rules
bspc rule -a Clandestine floating=on
bspc rule -a mpv floating=on
bspc rule -a gimp floating=on
bspc rule -a steam floating=on
bspc rule -a snes9x-gtk floating=on
bspc rule -a Screensaver floating=on
bspc rule -a zathura floating=on
bspc rule -a floating floating=on
bspc rule -a feh floating=on
bspc rule -a UE4Editor-Linux floating=on

# pad bar
bspc config -m HDMI-0 top_padding 20

if [ -f $HOME/.config/envrc ] ; then
	source $HOME/.config/envrc
else
	echo "[WARNING] NO ~/.config/envrc exists."
fi

if [ ! -z $SYSTEM ] ; then
	if [[ "$SYSTEM" == "desktop" ]] ; then
		bspc monitor DVI-1 -d 1 2 3 4 5
		bspc monitor HDMI-0 -d 6 7 8 9 10
	fi

	if [[ "$SYSTEM" == "laptop" ]] ; then
		bspc monitor eDP1 -d I II III IV V
		bspc monitor HDMI1 -d VI VII VIII IX X
	fi
fi

# start compositor
compton --config $HOME/.config/compton/compton.conf -b
