#!/bin/sh

#
# bspwm hotkeys
#

super + alt + Escape
    bspc quit

super + {_,shift + }w
    bspc node -{c,k}

super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

super + m
    bspc desktop -l next

super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

super + {_,shift + }c
    bspc node -f {next,prev}.local

super + {comma,period}
    bspc desktop -C {backward,forward}

super + bracket{left,right}
    bspc desktop -f {prev,next}

super + ctrl + {h,j,k,l}
    bspc node -p {left,down,up,right}

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'


#
# wm independent hotkeys
#

super + Return
    termite

super + shift + Return
    termite --class=custom_floating

super + d
    dmenu_wrapper

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd

super + {Left,Right}
    amixer sset Master {1%-,1%+} unmute

XF86Audio{Raise,Lower}Volume
    pactl set-sink-volume 1 {+1%,-1%}
    pactl set-sink-mute 1 0
    #amixer sset Master {1+,1-} unmute

XF86AudioMute
    pactl set-sink-mute 1 toggle
    #amixer -D pulse set Master toggle

#XF86MonBrightness{Up,Down}
super + {Up,Down}
    xbacklight {-inc,-dec} 1
