#!/bin/sh

bspc config border_width        2
bspc config window_gap         16

bspc config split_ratio         0.50
bspc config focus_by_distance   true

#bspc config borderless_monocle  true
#bspc config gapless_monocle     true

bspc monitor DVI-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

# pad bar
#bspc monitor HDMI-0 top_padding 20
#bspc monitor HDMI-0 --pad 20 0 0 0
bspc config -m HDMI-0 top_padding 20

compton --config /home/truncator/.config/compton/compton.conf -b

# loop
#if [ -e "$BSPWM_TREE" ] ; then
#	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
#rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
#fi
